### ISSUE TITLE
CLI usage

### ISSUE THREAD

**Issue by ivangretsky** [marceloucker/postcss-prefixer#20]
Good day!

Thanks for this useful plugin!
In the README you recommend to use this plugin with the postcss-cli: 

```
"scripts": {
    "postcss": "postcss input.css -u postcss-prefixer -o output.css"
}
```

Could you please explain how to pass the option to the cli.

**Comment by marceloucker** [comment]
Hi @ivangretsky,

https://github.com/postcss/postcss#npm-run--cli

According to the PostCSS docs, you should be able to pass a flag `-c` with a path for the PostCSS config file.

And to clarify, I'm not recommending using CLI, you can use any of the other options described on [PostCSS Usage](https://github.com/marceloucker/postcss-prefixer#usage) documentation, I'll be updating the README soon to make that clear.

**Comment by ivangretsky** [comment]
Thanks!
I did manage to make it work with a config option. But I thought it is possible to do it without an external config file. Maybe with something like [--env](https://github.com/postcss/postcss-cli#usage), but i don't know how.

**Comment by marceloucker** [comment]
@ivangretsky,

Cool, and yeah, it seems that the only way to pass options to plugins is by using a config file.

**Comment by ivangretsky** [comment]
Thank you!
