### ISSUE TITLE
Package does not run with node v6

### ISSUE THREAD

**Issue by baobaab** [marceloucker/postcss-prefixer#4]
Whereas the node engine version is `>=6.0.0` in `package.json`, the following code is not supported by node v6 :

```
    rule.selector = Tokenizer.stringify(interateSelectorNodes(
      Tokenizer.parse(selector),
      { prefix, ignore },
    ));
```
https://github.com/marceloucker/postcss-prefixer/blob/a8a5b881fea30fdc4a7cea7593319bbb3d680f9c/lib/prefixer.js#L69

**Comment by marceloucker** [comment]
Hi @baobaab ,

Object literal shorthand is supported since node v4: https://node.green/#ES2015-syntax-object-literal-extensions-shorthand-properties

Do you have any details on your issue?
