### ISSUE TITLE
why add prefix 'src-index' auto?

### ISSUE THREAD

**Issue by Sayid1** [marceloucker/postcss-prefixer#7]
Hello, however, this plugin is wonderful.
I using this plugin in my project. my webpack.config.js like this:
```javascript
...
         {
            loader: 'postcss-loader',
            options: {
              plugins() {
                return [
                  require('autoprefixer'),
                  require('postcss-prefixer')({
                    prefix: 'header-'
                  })
                ];
              },
            },
          },
...
```
# CSS 
```css
.header {
...
}
.brand {
...
}
```

# output
```css
.src-index__header-header {
...
}
.src-index__header-brand {
...
}

```

could you tell me  how 'src-index' it was added automatically?  
Thanks.

**Comment by marceloucker** [comment]
@Sayid1,

I wasn't able to reproduce the issue, could you provide the whole Webpack file?

Also, are you sure you do not have any other loader with the same purpose or even `postcss-loader` defined twice in the `use` array or in another rule?
